apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
data:
  CACHE_FILE: "/cache/carbon_cache.json"
  CARBON_AWARE_MODE: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-scheduler
  template:
    metadata:
      labels:
        app: custom-scheduler
    spec:
      serviceAccountName: custom-scheduler
      containers:
      - name: scheduler
        image: custom-scheduler:latest
        imagePullPolicy: Never
        env:
        - name: CACHE_FILE
          valueFrom:
            configMapKeyRef:
              name: scheduler-config
              key: CACHE_FILE
        - name: CARBON_AWARE_MODE
          valueFrom:
            configMapKeyRef:
              name: scheduler-config
              key: CARBON_AWARE_MODE
        volumeMounts:
        - name: cache-volume
          mountPath: /cache
        - name: kubeconfig
          mountPath: /root/.kube
          readOnly: true
      volumes:
      - name: cache-volume
        persistentVolumeClaim:
          claimName: carbon-cache-pvc
      - name: kubeconfig
        configMap:
          name: kubeconfig
          optional: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: custom-scheduler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-scheduler
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["pods/binding"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: custom-scheduler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: custom-scheduler
subjects:
- kind: ServiceAccount
  name: custom-scheduler
  namespace: default

