apiVersion: apps/v1
kind: Deployment
metadata:
  name: carbon-aware-scheduler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carbon-aware-scheduler
  template:
    metadata:
      labels:
        app: carbon-aware-scheduler
    spec:
      serviceAccountName: carbon-scheduler-sa
      containers:
      - name: carbon-scheduler
        image: carbon-scheduler:latest
        imagePullPolicy: Never  # For local development with minikube
        env:
        - name: ELECTRICITY_MAPS_API_KEY
          valueFrom:
            secretKeyRef:
              name: electricity-maps-secret
              key: api-key
        - name: DEFAULT_CARBON_ZONE
          value: "US-NY-NYIS"  # New York ISO zone
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: carbon-scheduler-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: carbon-scheduler-role
rules:
- apiGroups: [""]
  resources: ["nodes", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/binding"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: carbon-scheduler-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: carbon-scheduler-role
subjects:
- kind: ServiceAccount
  name: carbon-scheduler-sa
  namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: electricity-maps-secret
  namespace: kube-system
type: Opaque
data:
  # Base64 encoded API key - replace with your actual key
  # echo -n "your_api_key_here" | base64
  api-key: YWN4aDZmdEp2alRZcFVadmJCS3g=  # Your actual base64 encoded key
