apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatcher
  template:
    metadata:
      labels:
        app: dispatcher
    spec:
      schedulerName: custom-scheduler
      containers:
      - name: dispatcher
        image: dispatcher:latest
        imagePullPolicy: Never     # for local testing with minikube/kind
        ports:
        - containerPort: 8080
        env:
        # Use Kubernetes Secret for Electricity Maps API key
        # Create secret with: kubectl create secret generic electricity-maps-secret --from-literal=api-key=YOUR_API_KEY_HERE
        # Get your API key from: https://www.electricitymaps.com/
        - name: ELECTRICITY_MAPS_API_KEY
          valueFrom:
            secretKeyRef:
              name: electricity-maps-secret
              key: api-key
              optional: true
---
apiVersion: v1
kind: Service
metadata:
  name: dispatcher
spec:
  type: NodePort
  selector:
    app: dispatcher
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
