apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatcher
  template:
    metadata:
      labels:
        app: dispatcher
    spec:
      containers:
      - name: dispatcher
        image: dispatcher:latest
        imagePullPolicy: Never     # for local testing with minikube/kind
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dispatcher
spec:
  type: NodePort
  selector:
    app: dispatcher
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
